### ISSUE TITLE
Which index will influence a team's success?

### ISSUE THREAD

**Issue by Ranawu** [ZhangZeyu-UoE/DI-Sport-Analysis#2]

**Comment by Keqi-chen** [comment]
There are lots to information will influence the teams success.So it depends on how we thinking of it.According to the research paper "Game changer:The Topology of creativity ".The effects of structural folding on inventiveness and game changing creative success are especially strong when overlapping groups are cognitively distant.So we might to explore the diversity & cohesion factors of a team.That might influence a team's success.

**Comment by FinnKP** [comment]
I think diversity and cohesion could be useful indexes to measure. The main problem is our data is limited to only certain attributes of these indexes. Therefore we can't obtain fully accurate measures of diversity and cohesion. This is why we didn't see any clear correlation between diversity/cohesion and team performance. Of course, another issue could be the measure of team perfomance; although position in the league seems like an obvious indicator, there are other things that could be used to measure this (team pass success, team goal difference, team happiness etc.).

I would say cohesion and diversity still need to be explored, with their correlation to success. We just need a wider variety of measures to get a complete picture.

**Comment by Keqi-chen** [comment]
I think that we maybe choose a wrong way to explore the diversity and cohesion of a team.If we want to know which is the important index that influence the team performance.We can select several representative teams, and then analyze the teams' diversity and cohesion index from multiple angles (reverse research).Then infer which index is important.
